# -*- coding: utf-8 -*-
"""Calculadora de Viabilidade de Livro - Nicoll Siqueira da Rosa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bb0A1Ggzq5buWVRRfSpAVux8sy0G-cHw

# Calculadora de Viabilidade de Livro
Este código simula o cálculo de custos de produção de um livro, permitindo prever o lucro baseado na tiragem.
Esse é um cálculo muito usado em casas editoriais, principalmente através de planilhas, que serve para entender a viabilidade de um lançamento de livro ou de uma reimpressão.
"""

while True:
    print("Atenção: Use ponto (.) para decimais (preços). Exemplo: 50.90")

    print()

    # Inputs: custo de produção de cada exemplar, quantidade de exemplares da tiragem, preço para consumidor final, investimentos (revisão, diagramação, ilustração)

    nome = input("Qual é o nome do livro? ")
    tiragem = int(input("Quantos exemplares você quer imprimir? "))
    custo = float(input("Qual é o custo de produção de cada exemplar? R$"))
    preço = float(input("Qual será o preço de cada exemplar para o consumidor final? R$"))
    revisão = float(input("Quanto custou a revisão do livro? R$"))
    diagramação = float(input("Quanto custou a diagramação do livro? R$"))
    ilustração = float(input("Quanto custou a ilustração do livro? R$"))
    preço_papel = float(input("Qual é o preço do papel do livro? R$"))

    print()

    # Calculadora

    custo_tiragem = (custo * tiragem)
    investimento = (revisão + diagramação + ilustração + preço_papel)
    custo_total = (custo_tiragem + investimento)
    entrada = (preço * tiragem)
    lucro = (entrada - custo_total)
    percent_lucro = (lucro / entrada * 100)

    print(f"Custo da tiragem: R${(custo_tiragem):.2f}")
    print(f"Investimento: R${float(investimento):.2f}")
    print(f"Custo total: R${float(custo_total):.2f}")
    print(f"Entrada (Receita de venda): R${float(entrada):.2f}")
    print(f"Lucro: R${float(lucro):.2f}")
    print(f"Percentual de lucro: {float(percent_lucro):.2f}%")

    print()

      #Viablidade do projeto (projeto aceitável acima de 50% de lucro)

    if percent_lucro >= 80:
      print("Projeto viável com boa margem de lucro (acima de 80%)")
    elif percent_lucro >= 50:
      print("Projeto viável com margem de lucro aceitável (entre 50% a 80%)")
    else:
      print("Projeto inviável, com baixa margem de lucro (menos de 50%)")

    print()

    continuar = input("Deseja calcular outro livro? (s/n): ")
    if continuar == "n":
      print("Encerrando sistema...")
      break